### PR TITLE
Optimized for discord.js v13 and fixed some bugs

### PR DESCRIPTION
**Pull request by MrTwixxy**
I optimized and updated everything to discord.js v13, v12 isnt supported anymore. Also fixed some bugs

### CODE REVIEW

**Review by finnie2006 — APPROVED** [review]
I tested it and it works great for me

**Comment by ItsMitchh** [comment]
Currently undergoing testing now.

**Review by ItsMitchh — APPROVED** [review]
Testing on my local machine, this works fine, I'm happy to approve this in its current state.

**Comment by finnie2006** [comment]
Does this always take so long?  @SC2Mitch 
afbeelding

**Comment by ItsMitchh** [comment]
It's a known issue with Travis CI, be patient while a developer reviews this, thanks.

**Comment by finnie2006** [comment]
also after its merged the docker image should be rebuilded

**Comment by finnie2006** [comment]
I get this error when using docker version with the pr
npm ERR! missing script: azuri,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /home/node/.npm/_logs/2021-08-22T09_11_43_408Z-debug.log

Edit: also normal way idk why

**Comment by MrTwixxy** [comment]
Should be fixed now, forgot to add the script in package.json

**Comment by MrTwixxy** [comment]
Testing some stuff with Dockerfile right now

**Comment by MrTwixxy** [comment]
Finnie fixed the Dockerfile :)

**Comment by finnie2006** [comment]
There is still 1 bug sometimes it randomly stops playing the stream

**Comment by MrTwixxy** [comment]
I fixed the issue that the stream stops after a bit

**Comment by MrTwixxy** [comment]
Its fully done now, i managed to fix the bug (After many tries) where the bot get disconnected and stops te stream after a few minutes

**Comment by MrTwixxy** [comment]
I made a typo

**Pull request closed without merging**
